
baseurl = "https://cybersyndicates.com/"
title = "Cyber Syndicates"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "CyberSyndicates"
googleAnalytics = "UA-64026800-1"
disqusShortname = "cybersyndicates-com"


[Author]
    name = "Alexander Rymdeko-Harvey"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    titleheadline = "Red Team | Hacking | Infosec | TTPs"
	logo2 = "/logo.png"
    intro = true
    headline = "CybeЯ Syйdicдtes"
    description = "Red team and hacking blog with a touch of threat emulation of real world TTPs. We focus on Infosec and cover topics from latest toolsets!"
    github = "https://github.com/Cyber-Syndicates"
    gitlab = "https://github.com/Cyber-Syndicates"
    linkedin = "https://linkedin.com/in/"
    gplus = "https://google.com/"
    twitter = "https://twitter.com/cybersyndicates"
    stackoverflow = "https://stackoverflow.com/users/"
    youtube = "https://www.youtube.com/user/Rymdeko"
    opengraph = true


[Permalinks]
    post = "/:year/:month/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Presentations"
    url = "/presentations/"
    weight = 2

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 4

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 5

[[menu.main]]
    name = "The Team"
    url = "/page/team/"
    weight = 6

